### PR TITLE
Added support for JPQL IN clause

### PR DESCRIPTION
**Pull request by levants**
via new static method org.jinq.jpa.JPQL.in(java.lang.Object,
java.util.Collection)
or java.util.List.contains(java.lang.Object) and
java.util.Set.contains(java.lang.Object) methods
with appropriate unit tests

### CODE REVIEW

**Comment by my2iu** [comment]
Thanks, I'll take a look at this soon. I should have probably implemented it myself, but I forgot about it since it's possible to emulate the operation using subqueries.

**Comment by my2iu** [comment]
Actually, give me a week or so to think about this. I might want to implement more general support for IN (such as in subqueries and adding it to the streams), but I have to think through the details.

**Comment by levants** [comment]
It's OK.
I think IN and EXISTS for subqueries will be great, but in my opinion Collection parameters and subquery streams should be different.
For me as for user Collection.contains method seems quiet natural and simple when I need Set or List as parameter.

**Comment by my2iu** [comment]
Ok, I've made a JPQL.isInList() and JPQL.listContains() that should provide the same functionality as in your changes, but can also handle some limited subqueries. I'll be making additional changes during the week to get better subquery support going.

**Pull request closed without merging**
